export default  [
    {
        name:"environmentMapTexture",
        type:"cube",
        path:[
            "/textures/cube/ambident.jpg",
            "/textures/cube/color.jpg",
            "/textures/cube/displacement.jpg",
            "/textures/cube/normal.jpg",
            "/textures/cube/normalGl.jpg",
            "/textures/cube/roughness.jpg",
        ]
    },
    {
        name:"treeTexture",
        type:"texture",
        path:[
            "/textures/tree/leaves2.png"
        ]
    },
    {
        name:"treeGlb",
        type:"gltf",
        path:[
            "/models/tree.glb"
        ]
    },
    {
        name:"bushTexture",
        type:"texture",
        path:[
            "/textures/tree/leaves.png"
        ]
    },
]